import { MovieDetailType } from "../interfaces/api";

export const FILM_MOCK_DATA: MovieDetailType = {
  id: 3,
  title: "Something Title",
  releaseDate: "May 19, 1999",
  director: "Jonny Sins",
  producer: "Jonny Stark",
  description:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur asperiores fugit nostrum quaerat voluptatem dicta id dolorum modi dignissimos eum, magni alias, voluptate culpa tempora unde quos architecto assumenda eligendi. Consequatur asperiores fugit nostrum quaerat voluptatem dicta id dolorum modi dignissimos eum, magni alias, voluptate culpa tempora unde quos architecto assumenda eligendi.",
  characters: [
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
    "Nikkar",
    "Saitama",
    "Genos",
    "Yoda",
  ],
  planets: [
    "Earth",
    "EA-45",
    "Youranus",
    "Earth",
    "EA-45",
    "Youranus",
    "Earth",
    "EA-45",
    "Youranus",
    "Earth",
    "EA-45",
    "Youranus",
    "Earth",
    "EA-45",
    "Youranus",
  ],
  species: ["Cat", "Dog", "Cat", "Dog", "Cat", "Dog"],
  starships: [],
  vehicles: ["Car", "Fly"],
};
